version: '3.8'

services:
  db:
    build: ./postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  python_service:
    build: ./python_microservice
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/fastapi_db
  go_service:
    build: ./go_microservice
    volumes:
      - ./src:/app/src
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/fastapi_db

volumes:
  postgres_data: